---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_install_options: -P chefdk
  chef_omnibus_root: /opt/chefdk

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[chef_delivery::default]
    attributes:
